		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="mymemo" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="MyMemo, il miglior gioco per stimolare la tua memoria!">
		<meta name="author" content="Ravasi - Ghiani - Pavesi - Tavaroli">
		<link rel="icon" href="resources/favicon.ico">
		

		<link href="css/theme.css" rel="stylesheet">