			<!-- TODO: rimuovere e integrare in altri .js di nostra mano
   			================================================== 
    		<script  type="text/javascript" src="js/external/jquery1.11.2.min.js"></script>
    		<script  type="text/javascript" src="js/external/bootstrap.min.js"></script>
-->
			<!-- ================================================== -->
			
			<script type="text/javascript" src="js/stringLib.js"></script>
			<script type="text/javascript" src="js/netLib.js"></script>
			<script type="text/javascript" src="js/graphicLib.js"></script>			
			<!--  Dizionario per i messaggi -->
			<script type="text/javascript" src="js/dictionary.js"></script>
			<script type="text/javascript" src="js/login.js"></script>